"""init

Revision ID: 559f78b0fd0f
Revises: 
Create Date: 2024-08-29 16:44:21.424717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '559f78b0fd0f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id')
    )
    op.create_table('merchant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('merchant_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('merchant_id')
    )
    op.create_table('payment_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_number', sa.String(), nullable=False),
    sa.Column('card_type', sa.String(), nullable=False),
    sa.Column('exp_year', sa.Integer(), nullable=False),
    sa.Column('exp_month', sa.Integer(), nullable=False),
    sa.Column('name_on_card', sa.String(), nullable=False),
    sa.Column('save_details', sa.Boolean(), nullable=False),
    sa.Column('cvv', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('billing_address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('mobile_no', sa.String(), nullable=False),
    sa.Column('email_id', sa.String(), nullable=False),
    sa.Column('address_line_1', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('zip', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.customer_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('txn_amount', sa.Numeric(), nullable=False),
    sa.Column('payment_type', sa.String(), nullable=False),
    sa.Column('currency_code', sa.String(), nullable=False),
    sa.Column('txn_reference', sa.String(), nullable=False),
    sa.Column('seriestype', sa.String(), nullable=True),
    sa.Column('method', sa.String(), nullable=True),
    sa.Column('success_url', sa.String(), nullable=False),
    sa.Column('fail_url', sa.String(), nullable=False),
    sa.Column('merchant_id', sa.String(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('payment_detail_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.customer_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchant.merchant_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payment_detail_id'], ['payment_detail.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction')
    op.drop_table('billing_address')
    op.drop_table('payment_detail')
    op.drop_table('merchant')
    op.drop_table('customer')
    # ### end Alembic commands ###
